### PR TITLE
Add Visual Basic and VBScript support

### PR DESCRIPTION
**Pull request by dgmdan**
This adds support for indenting Visual Basic and VBScript languages. These languages are still widely used and even their native IDE Visual Studio lacks a code beautifier feature.

### CODE REVIEW

**Comment by dgmdan** [comment]
bump

**Comment by akalongman** [comment]
I am on vacation now, I will review pull request in next weeks. Thank you for help

**Comment by thecotne** [comment]
@dgmdan add VBScript in readme

**Comment by dgmdan** [comment]
@thecotne sure, I've added this.

**Comment by om-nishu-trantor** [comment]
@akalongman Any updates to merge this up ?

**Comment by thecotne** [comment]
@akalongman looks good to me merging 

i think we can merge some pull requests then check to see it is not broken and release new version if not

**Pull request merged**
