### PR TITLE
Coldfusion formatter code

### PR DESCRIPTION
**Pull request by elpeix**

### CODE REVIEW

**Comment by RobertJGabriel** [comment]
any update on this :)

**Comment by thecotne** [comment]
@elpeix what is coldfision and is it any different from html formatter?

**Comment by RobertJGabriel** [comment]
@elpeix Coldfusion is a programming languages developed by Adobe , not really that popular as it used to be but still used a lot. It's similar to PHP and is a server langue.

In ColdFusion you can mix HTML and ColdFusion to create and serve pages.

**Comment by elpeix** [comment]
There are some differences between Coldfusion and HTML, but the syntax is similar when you use Coldfusion Markup (You can programming in Coldfusion Script or cfscript, similar to Javascript). 

Coldfusion Markup is not really xml  because it does not respect its specs in some cases. 

Coldfusion language is also used on Railo, Lucee and maybe it is on others free platforms.

**Comment by akalongman** [comment]
@elpeix please rewrite your pull request for removing conflicts and send PR to me. I will merge

**Pull request closed without merging**
