### PR TITLE
Fix & expand HTML Formatter (and ColdFusion Formatter)

### PR DESCRIPTION
**Pull request by RevanProdigalKnight**
Fixes issues discussed in PR #144 and the separate issue I created in #194 for tag attribute expansion, as well as adding support for reducing empty tags on custom tag names as requested in #190, and custom singleton tags as requested in #177.

I also went in and updated the relevant code in the ColdFusion Formatter (since it's based on the HTML formatter), so @elpeix, if you want to take a look through my changes there to make sure I didn't break anything important, feel free.

### CODE REVIEW

**Comment by RevanProdigalKnight** [comment]
Added another line to fix an issue where the HTML/ColdFusion formatters would break AngularJS/Blade brace templates into multiple lines.

Should also address #193

**Comment by elpeix** [comment]
It seems good, go ahead!

**Comment by akalongman** [comment]
@RevanProdigalKnight thank you for your work! your PR is tested? I will merge it today

**Comment by RevanProdigalKnight** [comment]
@akalongman It is tested for all the issues that it is supposed to address.

**Pull request merged**
