### PR TITLE
Changed Formatters from hard coded to settings based.

### LINKED ISSUE #43: New format for codeformatter
Hi,

I am using Laravel (.blade.php) files and I'd like to format my HTML with this extension.
Now, I need to set my format to HTML and then format my code. I think it should be an easy thing to do but couldn't find it out.

Best regards

### PR DESCRIPTION
**Pull request by jameskopacz**
This is an attempt to fix #43 and #127.

In 43 you could add ```laravel blade highlighter``` to the html formatters option and in 127 you could add ```javacsriptnext - es6 syntax```  to the js formatters option. This would also remove the need in the future to add formatters into the code base as done in #72 / #83.

### CODE REVIEW

**Comment by thecotne** [comment]
fixes #150

**Comment by thecotne** [comment]
@akalongman is this already implemented? 

https://github.com/akalongman/sublimetext-codeformatter/blob/master/codeformatter/formatter.py#L49

**Comment by akalongman** [comment]
@thecotne already implemented, but not released yet

**Comment by thecotne** [comment]
@jameskopacz so this feature will be in next release closing this pull request since we don't need to merge it

will close #43 after next release

**Pull request closed without merging**
