### PR TITLE
Make HTML Beautifier more powerful

### PR DESCRIPTION
**Pull request by RevanProdigalKnight**
The current HTML Beautifier doesn't attempt very much on files that are not already partly beautified by the user, which makes it difficult to find things in code-generated HTML code.

This fixes the aforementioned problems with the current HTML beautifier by forcing all tags to appear on their own lines and then coercing indentation on all tags that are not defined in the HTML5 spec as "void" tags.

It also adds new configuration options:
- `expand_javascript`: Expand and format (minified?) Javascript/CSS inside an HTML file
- `expand_tags`: Expand tags with multiple attributes to multiple lines
  - `minimum_attribute_count`: The minimum number of attributes a tag should have before it is expanded to multiple lines
- `exception_on_tag_mismatch`: Performs basic tag "matching" by throwing an exception if the end indentation is not equal to `0`. Since the HTML Beautifier still doesn't employ a full-on parser, I didn't go further than that
- `reduce_empty_tags`: If a tag contains no content, it (and its matching end tag, if any) will be put on a single line with no space in between

The following configuration options were removed because the new implementation does not support them:
- `preserve_newlines`
- `max_preserve_newlines`

The option `indent_tags` was removed because the new implementation indents all tags that are not defined by the HTML 5 spec to be "void" (a tag that can end itself, also known as a singleton), and those tags are now defined inside the HTML Beautifier

The HTML Beautifier's output now much more closely resembles that of [JSBeautifier.org](http://jsbeautifier.org/)'s regardless of the original file structure, with the only major exceptions being that the `head` and `body` tags are indented inside of the `body` tag (as opposed to being on the same level of indentation), and newlines are not preserved.

Example Input:
```
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>GHS Single Sign-On Portal</title><!--[if IE 9]><link href="/openam/css/ie9.css" rel="stylesheet" type="text/css"/><![endif]--><!--[if lte IE 7]><link href="/openam/css/ie7.css" rel="stylesheet" type="text/css"/><![endif]--><script language="JavaScript" src="/openam/js/auth.js" type="text/javascript"></script><link rel="stylesheet" type="text/css" href="/openam/vendor/bootstrap/css/bootstrap.min.css"/></head><body><style>@media (max-height: 349px) {.login-container {margin:25px 0;}}@media (min-height: 350px) {.login-container {position:absolute;top:50%;transform:translateY(-50%);}}body {background:#eeecea url(../images/login-bg.png) top left no-repeat;background-size:100% auto;}.login-container {background:#fff;border-radius:4px;}.login-container img.ghs-logo {max-width:100%;position:relative;left:50%;transform:translateX(-50%);}.copyright {text-align:center;font-size:.75em;}</style><div class="col-xs-12 col-sm-8 col-sm-push-2 col-md-6 col-md-push-3 col-lg-4 col-lg-push-4 login-container"><img class="ghs-logo" src="../images/logo.png" alt="GHS, an Emdeon company"/><form class="form-horizontal" name="Login" action="/openam/UI/Login" method="post"><fieldset><div class="form-group"><label class="col-xs-3 control-label" for="IDToken1">Username</label><div class="col-xs-9"><input class="form-control" name="IDToken1" id="IDToken1" placeholder="Username" type="text" autofocus="true"/></div></div><div class="form-group"><label class="col-xs-3 control-label" for="IDToken2">Password</label><div class="col-xs-9"><input class="form-control" name="IDToken2" id="IDToken2" placeholder="Password" type="password" autofocus="true"/></div></div><input name="goto" value="aHR0cDovL3dnZWhyaW5nMi5naHNpbmMuY29tOjgwODAvYW5ndWxhci8=" type="hidden"/><input name="gotoOnFail" value="" type="hidden"/><input name="SunQueryParamsString" value="" type="hidden"/><input name="encoded" value="true" type="hidden"/><input name="gx_charset" value="UTF-8" type="hidden"/><div class="form-group"><button class="btn btn-primary col-xs-2 col-xs-offset-5" name="Login.Submit" onclick="this.disabled = true;" type="submit">Log In</button></div></fieldset></form><p class="copyright text-muted">Copyright © 2008-2013, ForgeRock AS. All Rights Reserved. Use of this software is subject to the terms and conditions of the ForgeRock™ License and Subscription Agreement.</p></div><script>// This is effectively an Array().some() loop, but the HTMLCollection object in browsers doesn't support that despite being a glorified array(function(inputs) {for (let input of inputs) {if (input.autofocus) {input.focus();break;}}}(document.getElementsByClassName('form-control')));</script></body></html>
```
Example Output:
```
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>
      GHS Single Sign-On Portal
    </title>
    <!--[if IE 9]>
      <link href="/openam/css/ie9.css" rel="stylesheet" type="text/css"/>
    <![endif]-->
    <!--[if lte IE 7]>
      <link href="/openam/css/ie7.css" rel="stylesheet" type="text/css"/>
    <![endif]-->
    <script language="JavaScript" src="/openam/js/auth.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="/openam/vendor/bootstrap/css/bootstrap.min.css"/>
  </head>
  <body>
    <style>
      @media (max-height: 349px) {
        .login-container {
          margin:25px 0;
        }
      }
      @media (min-height: 350px) {
        .login-container {
          position:absolute;
          top:50%;
          transform:translateY(-50%);
        }
      }
      body {
        background:#eeecea url(../images/login-bg.png) top left no-repeat;
        background-size:100% auto;
      }
      .login-container {
        background:#fff;
        border-radius:4px;
      }
      .login-container img.ghs-logo {
        max-width:100%;
        position:relative;
        left:50%;
        transform:translateX(-50%);
      }
      .copyright {
        text-align:center;
        font-size:.75em;
      }
    </style>
    <div class="col-xs-12 col-sm-8 col-sm-push-2 col-md-6 col-md-push-3 col-lg-4 col-lg-push-4 login-container">
      <img class="ghs-logo" src="../images/logo.png" alt="GHS, an Emdeon company"/>
      <form class="form-horizontal" name="Login" action="/openam/UI/Login" method="post">
        <fieldset>
          <div class="form-group">
            <label class="col-xs-3 control-label" for="IDToken1">
              Username
            </label>
            <div class="col-xs-9">
              <input class="form-control" name="IDToken1" id="IDToken1" placeholder="Username" type="text" autofocus="true"/>
            </div>
          </div>
          <div class="form-group">
            <label class="col-xs-3 control-label" for="IDToken2">
              Password
            </label>
            <div class="col-xs-9">
              <input class="form-control" name="IDToken2" id="IDToken2" placeholder="Password" type="password" autofocus="true"/>
            </div>
          </div>
          <input name="goto" value="aHR0cDovL3dnZWhyaW5nMi5naHNpbmMuY29tOjgwODAvYW5ndWxhci8=" type="hidden"/>
          <input name="gotoOnFail" value="" type="hidden"/>
          <input name="SunQueryParamsString" value="" type="hidden"/>
          <input name="encoded" value="true" type="hidden"/>
          <input name="gx_charset" value="UTF-8" type="hidden"/>
          <div class="form-group">
            <button class="btn btn-primary col-xs-2 col-xs-offset-5" name="Login.Submit" onclick="this.disabled = true;" type="submit">
              Log In
            </button>
          </div>
        </fieldset>
      </form>
      <p class="copyright text-muted">
        Copyright © 2008-2013, ForgeRock AS. All Rights Reserved. Use of this software is subject to the terms and conditions of the ForgeRock™ License and Subscription Agreement.
      </p>
    </div>
    <script>
      // This is effectively an Array().some() loop, but the HTMLCollection object in browsers doesn't support that despite being a glorified array
      (function(inputs) {
        for (let input of inputs) {
          if (input.autofocus) {
            input.focus();
            break;
          }
        }
      }
      (document.getElementsByClassName('form-control')));
    </script>
  </body>
</html>
```

### CODE REVIEW

**Comment by dgmdan** [comment]
This looks pretty handy. I'd be happy to see it merged in.

**Comment by aske-cph** [comment]
Hi, 

I have added the options to my 

> user/preferences.sublime-settings


```
{
    "codeformatter_html_options":
    {
        "expand_tags": true,
        "minimum_attribute_count" : 2
    }
}
```

When running codeformatter "Format as HTML" attributes aren't expanded. For example this line:

`<ui-select on-select="save()" reset-search-input="true" fix-focus-ui-select minimum-input-length="5" ng-model="courseLeader.selected" theme="bootstrap">`

Should get expanded right? But it doesn't. Are my preferences in the correct place?

**Comment by RevanProdigalKnight** [comment]
That's odd. I just tried that myself and it worked (nearly) correctly with and without the closing tag. The attribute without an `=` didn't get put on its own line, instead being put with the `minimum-input-length` attribute.

Using these custom settings:
```
{
	"codeformatter_html_options":
	{
		"expand_tags": true,
		"minimum_attribute_count": 2
	}
}
```

This is the output I got:
```
<ui-select on-select="save()"
           reset-search-input="true"
           fix-focus-ui-select minimum-input-length="5"
           ng-model="courseLeader.selected"
           theme="bootstrap">
```

I guess for now try copying my settings block verbatim, though I don't think your block has any typos.

**Comment by aske-cph** [comment]
Ahh, i see.

I had put the settings in my user preferences not in a separate codeformatter preference file.

Thanks for the elaborate response ( Your path lead me to the error ), and thanks for the great addition to the library!

It works perfectly now!

**Comment by RevanProdigalKnight** [comment]
Glad I could be of help. It seems I still need to work on the attribute separation, though, since it doesn't separate out attributes without an `="<some text>"` after them.

**Comment by aske-cph** [comment]
Yep it seems some attributes doesn't get expanded. I tried to set

`minimum-attribute-count`

To 1. But this line only gets partially expanded.. Or is this expected behaviour?
```

				<ui-select-choices repeat="person in teachersFiltered | filter:$select.search | limitTo: 7"
								   position='down' ng-show="$select.search.length >1">
```

**Pull request merged**
